### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type function

### ISSUE THREAD

**Issue by benmwendwa** [BoLaMN/ajv-bsontype-coerce#1]
I'm getting this error when I try using the package.
```
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type function
    at Function.from (buffer.js:293:9)
    at fnv1a32 (/...project_folder.../node_modules/ajv-bsontype-coerce/node_modules/bson/lib/bson/fnv1a.js:21:25)
    at fnv1a24 (/...project_folder.../node_modules/ajv-bsontype-coerce/node_modules/bson/lib/bson/fnv1a.js:39:18)
    at Object.<anonymous> (/...project_folder.../node_modules/ajv-bsontype-coerce/node_modules/bson/lib/bson/objectid.js:14:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```
My node.js version is `12.12.0`, what could be the cause of this?

**Comment by BoLaMN** [comment]
the module isnt in a working completed state

it was an extension to my ajv-bsontype module but i wasnt able to make it work due to restrictions from the main ajv module

**Comment by deepsea** [comment]
Have a similar issue. How did you resolve this?

yarn run v1.22.4
$ nodemon --inspect=5858 -r ts-node/register src/js/index.ts
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --inspect=5858 -r ts-node/register src/js/index.ts`
Debugger listening on ws://127.0.0.1:5858/XXXX-XXXX-XXXX-XXXX
For help, see: https://nodejs.org/en/docs/inspector
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received function hidden
    at Function.from (buffer.js:327:9)
    at fnv1a32 (C:\Audi\trunk\node_modules\bson\lib\bson\fnv1a.js:21:25)
    at fnv1a24 (C:\Audi\trunk\node_modules\bson\lib\bson\fnv1a.js:39:18)
    at Object.<anonymous> (C:\Audi\trunk\node_modules\bson\lib\bson\objectid.js:14:20)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
[nodemon] app crashed - waiting for file changes before starting...
